task 4
Zoba1/lesson_1_and_2_task_4_Chizoba_Adigwe pull request #1
Opened 2023-04-28 15:53 UTC by Zoba1

i am done with my task 4 please review
@chidipatrick
@promise-J

2023-05-02 15:15 UTC, promise-J approved these changes
@Zoba1 , please add the tab logo for the page.

2023-05-03 14:49 UTC, ChidiPatrick commented on html/index.html
> +                <a name="section"></a>
This anchor element has no content. Add the content, and the "href" attribute and value.

2023-05-03 14:56 UTC, ChidiPatrick requested changes
Fix the anchor tag issue I commented on down there

2023-05-04 09:48 UTC, ChidiPatrick approved these changes
Great job, keep it up

2023-05-04 10:19 UTC, merged